## Plotting My Area

Use the starter code below to explore the data for your area

In [0]:
src_path_base = "dbfs:/databricks-datasets/COVID/CSSEGISandData/csse_covid_19_data/csse_covid_19_daily_reports/"
dest_path_base = "file:////tmp/covid_daily_reports/"

files = [
 '11-21-2020.csv',
 '11-22-2020.csv',
 '11-23-2020.csv',
 '11-24-2020.csv',
 '11-25-2020.csv',
 '11-26-2020.csv',
 '11-27-2020.csv',
 '11-28-2020.csv',
 '11-29-2020.csv',
 '11-30-2020.csv'
]

all_files = []

for file in files:
  filename = dest_path_base+file
  dbutils.fs.cp(src_path_base+file, filename)
  all_files.append(filename)

all_files

In [0]:
import datetime
import pandas as pd

dfs = []

for filename in all_files:
  temp_df = pd.read_csv(filename)
  temp_df.columns = [c.replace("/", "_") for c in temp_df.columns]
  temp_df.columns = [c.replace(" ", "_") for c in temp_df.columns]
  
  month, day, year = filename.split("/")[-1].replace(".csv", "").split("-")
  d = datetime.date(int(year), int(month), int(day))
  temp_df["Date"] = d

  dfs.append(temp_df)
  
all_days_df = pd.concat(dfs, axis=0, ignore_index=True, sort=False)
all_days_df = all_days_df.drop(["Lat", "Long_", "FIPS", "Combined_Key", "Last_Update"], axis=1)

all_days_df.head(10)

,Admin2,Province_State,Country_Region,Confirmed,Deaths,Recovered,Active,Incident_Rate,Case_Fatality_Ratio,Date
0,NaN,NaN,Afghanistan,44503,1675,35422,7406.0,114.320310,3.763791,2020-11-21
1,NaN,NaN,Albania,32196,685,15469,16042.0,1118.771284,2.127593,2020-11-21
2,NaN,NaN,Algeria,73774,2255,48183,23336.0,168.237732,3.056632,2020-11-21
3,NaN,NaN,Andorra,6207,76,5290,841.0,8033.391574,1.224424,2020-11-21
4,NaN,NaN,Angola,14413,336,7273,6804.0,43.853473,2.331229,2020-11-21
5,NaN,NaN,Antigua and Barbuda,139,4,128,7.0,141.941018,2.877698,2020-11-21
6,NaN,NaN,Argentina,1366182,36902,1187053,142227.0,3022.808967,2.701104,2020-11-21
7,NaN,NaN,Armenia,124839,1931,92829,30079.0,4212.930872,1.546792,2020-11-21
8,NaN,Australian Capital Territory,Australia,115,3,111,1.0,26.862883,2.608696,2020-11-21
9,NaN,New South Wales,Australia,4538,53,3173,1312.0,55.900468,1.167915,2020-11-21